print("Installing GimpOCD-V2...")
print("Creating directories...")
os.execute("mkdir /home/GimpOCD-V2")
os.execute("mkdir /home/GimpOCD-V2/displays")
os.execute("mkdir /home/GimpOCD-V2/displays/glasses_elements")
os.execute("mkdir /home/GimpOCD-V2/displays/modules")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/item_overseer")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/machine_overseer")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/me_cpu_controller")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/power_overseer")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/robot_director")
os.execute("mkdir /home/GimpOCD-V2/displays/modules/text_editor")
os.execute("mkdir /home/GimpOCD-V2/lib")

os.execute("mkdir /usr/bin")
os.execute("wget https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/GimpOCD.lua /usr/bin/GimpOCD.lua")

print("Downloading files...")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/GimpOCD_mk2.lua /home/GimpOCD-V2/GimpOCD_mk2.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/glasses_display.lua /home/GimpOCD-V2/displays/glasses_display.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/glasses_elements/contextMenu.lua /home/GimpOCD-V2/displays/glasses_elements/contextMenu.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/glasses_elements/hudSetup.lua /home/GimpOCD-V2/displays/glasses_elements/hudSetup.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/modules.lua /home/GimpOCD-V2/displays/modules/modules.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/item_overseer/item_overseer.lua /home/GimpOCD-V2/displays/modules/item_overseer/item_overseer.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/machine_overseer/machine_overseer.lua /home/GimpOCD-V2/displays/modules/machine_overseer/machine_overseer.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/me_cpu_controller/me_cpu_controller.lua /home/GimpOCD-V2/displays/modules/me_cpu_controller/me_cpu_controller.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/power_overseer/power_overseer.lua /home/GimpOCD-V2/displays/modules/power_overseer/power_overseer.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/robot_director/robot_director.lua /home/GimpOCD-V2/displays/modules/robot_director/robot_director.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/displays/modules/text_editor/text_editor.lua /home/GimpOCD-V2/displays/modules/text_editor/text_editor.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/lib/gimp_colors.lua /home/GimpOCD-V2/lib/gimp_colors.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/lib/gimpHelper.lua /home/GimpOCD-V2/lib/gimpHelper.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/lib/PagedWindow.lua /home/GimpOCD-V2/lib/PagedWindow.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/lib/timing.lua /home/GimpOCD-V2/lib/timing.lua")
os.execute("wget -f https://raw.githubusercontent.com/Gimpeh/GimpOCD-V2/refs/heads/main/lib/widgetsAreUs.lua /home/GimpOCD-V2/lib/widgetsAreUs.lua")

print("Installation complete!")
print("run GimpOCD from the command line to start")
print("If accelerating, include the acceleration multiplier as an arg (e.g. GimpOCD 128)")